CREATE TABLE exemple
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    commentaire VARCHAR(2048)                           NOT NULL,
    my_number   INTEGER,
    CONSTRAINT pk_exemple PRIMARY KEY (id)
);